# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
      with:
        # ... other options
        plugin_pagespeed: yes
        plugin_pagespeed_token: ${{ secrets.PROFILE_STATS_TOKEN }} # Optional but recommended
        plugin_pagespeed_detailed: yes                         # Print detailed audit metrics
        plugin_pagespeed_screenshot: no                        # Display a screenshot of your website
        plugin_pagespeed_url: .user.website                    # Website to audit (defaults to your GitHub linked website)